### ISSUE TITLE
Global Cache IP2SL not sending serial

### ISSUE THREAD

**Issue by pieterhuijgen** [bitfocus/companion-module-globalcache-itac-sl#2]
I try to send a command using the IP2SL connection, however nothing happens. If i try the IP2CC (relay) it works. The command is someting like 50701% (without carriage return).
When I use Global Cache iTest I'm only able to send this command by selecting serial1, port 4999.
Commands use port 4998, so that might cause it. 
Is there any way to solve it, i.e. to change the port number or make it adjustable?

**Comment by cxselph** [comment]
@pieterhuijgen I am going to close this for now. If you have a chance to work with the IP2SL again and still have trouble, let us know. Also I added an option to change how the command is terminated. It originally was doing a carriage return and line feed. Now you can choose one, the other, or both. I am still waiting on those changes to be approved and added to the core build.
