### ISSUE TITLE
Hex or ASCII

### ISSUE THREAD

**Issue by vibinc901** [bitfocus/companion-module-globalcache-itac-sl#3]
I've tried using the IP2SL module to control a Sony MCS-8 switcher. The switcher's control code is 8 bit Hex. When I put the control code into the IP2SL module and trigger, nothing happens. When I use the same code with my USB to Serial cable and CoolTerm, it switches the device.

The IP2SL is connecting to Companion, and the green serial light lights up when I trigger the command, so I know its getting the instruction from Companion. But I'm wondering if the command its sending is Hex or ASCII text. 

I've got all the hex codes for PV/PGM/Aux1/Aux2 for the MCS8 cataloged, so if we can get this to work, I could also contribute the codes so a module for that switcher could be added.

Thanks in advance.

**Comment by haakonnessjoen** [comment]
Do yo use the "HEX" checkbox in "Send string" in CoolTerm?

**Comment by vibinc901** [comment]
Yes, I believe so. 

> Do yo use the "HEX" checkbox in "Send string" in CoolTerm?

**Comment by haakonnessjoen** [comment]
Fixed in bitfocus/companion@1a9dbcc, added a new "Send hex command" option
